#! /usr/bin/env python

import database
import timestamp


import json
import sys
import yaml



def main() -> None:
    """Entry point"""

    db = database.Database()
    ts = timestamp.Timestamp()

    if len(sys.argv) < 4:
        raise Exception(f"Usage: {sys.argv[0]}: type from_date_time to_date_time")
    type: str = sys.argv[1]
    from_str: str = sys.argv[2]
    to_str: str = sys.argv[3]

    min_stamp = ts.iso_to_timestamp(from_str)
    max_stamp = ts.iso_to_timestamp(to_str)

    print(yaml.dump(db.files_in_range(min_stamp, max_stamp)))
    print(yaml.dump(db.entries_in_range(min_stamp, max_stamp, type)))

if __name__ == "__main__":
    main()
